#!/bin/sh
### BEGIN INIT INFO
# Provides:       wcproducts
# Required-Start: $network $remote_fs 
# Required-Stop:  $network $remote_fs 
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Short-Description: s3ql Init Script
# Description:  s3ql Init Script
### END INIT INFO

#! /bin/bash

# Configuration
BUCKET="s3://your-bucket-name-here"
MOUNTPOINT="/mnt/your/mount/point/here"

LOGFILE="/var/log/s3ql.log"

case "$1" in
  start)
    echo "Starting s3ql"
    mkdir -p "$MOUNTPOINT"
    chown bitnami.daemon "$MOUNTPOINT"
    chmod gu+rw "$MOUNTPOINT"
    fsck.s3ql --batch "$BUCKET" 2>&1 | cat >> "$LOGFILE"
    mount.s3ql --allow-other "$BUCKET" "$MOUNTPOINT" 2>&1 | cat >> "$LOGFILE"
    chown -R bitnami.daemon "$MOUNTPOINT"
    chmod -R gu+rw "$MOUNTPOINT"
    ;;
  stop)
    echo "Stopping s3ql"
    umount.s3ql "$MOUNTPOINT"
    ;;
  *)
    echo "Usage: /etc/init.d/s3ql {start|stop}"
    exit 1
    ;;
esac

exit 0

